version: "3"
services:
#  go-api-json-rpc:
#    build:
#      context: .
#      dockerfile: ./.img/go/Dockerfile
#    ports:
#      - '80:1234'
#    volumes:
#      - ./:/app
#    links:
#      - postgres
#    environment:
#      PGHOST: 'postgres'
#      PGDATABASE: 'in_scanner'
#      PGUSER: 'in_scanner'
#      PGPASSWORD: 'pass_postgres'
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'in_scanner'
      POSTGRES_PASSWORD: 'pass_postgres'
      POSTGRES_DB: 'in_scanner'
    volumes:
      - database_data:/var/lib/postgresql/data
      - .img/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  database_data:
    driver: local