version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'in_scaner'
      POSTGRES_PASSWORD: 'pass_postgres'
      POSTGRES_DB: 'in_scaner'
    volumes:
      - database_data:/var/lib/postgresql/data
      - .img/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  database_data:
    driver: local